parameters:
  monolog.logger.connection: 'connection'

services:
  json.encoder:
    class: Vain\Core\Encoder\Json\JsonEncoder
  json.decoder:
    alias: json.encoder
  counter:
    class: Vain\Core\Counter\Counter
    shared: false
  connection.storage:
    class: Vain\Core\Connection\Storage\ConnectionStorage
    arguments: ['@config']
  monolog.logger.connection:
    class: Monolog\Logger
    arguments: ['%monolog.logger.connection%']
  logger.connection:
    class: Vain\Logger\Monolog\MonologAdapter
    arguments: ['@monolog.logger.connection']
    tags:
      - {name: logger}
  database.generator.factory:
    class: Vain\Core\Database\Generator\Factory\DatabaseGeneratorFactory
  database.storage:
    class: Vain\Core\Database\Storage\DatabaseStorage
    arguments: ['@connection.storage', '@config']
  operation.collection.factory.transaction:
    class: Vain\Core\Database\Operation\Collection\Factory\Decorator\Transaction\CollectionFactoryTransactionDecorator
    decorates: operation.collection.factory
    decoration_priority: 200
    arguments: ['@operation.collection.factory.transaction.inner', '@database.mvcc']
