imports:
  - { resource: '../di.yml' }

services:
  api.config.factory.assert:
    class: Vain\Core\Api\Config\Factory\Decorator\Assert\ApiConfigFactoryAssertDecorator
    decorates: api.config.factory
    decoration_priority: 1000
    arguments: ['@api.config.factory.assert.inner']
  api.config.parameter.factory.assert:
    decorates: api.config.parameter.factory
    decoration_priority: 1000
    class: Vain\Core\Api\Config\Parameter\Factory\Decorator\Assert\ApiParameterConfigFactoryAssertDecorator
    arguments: ['@api.config.parameter.factory.assert.inner']
  api.command.tracker:
    class: Vain\Core\Api\Request\Tracker\Trust\ApiTrustTracker
    arguments: ['@api.command.security']
  app.context.factory.config.assert:
    class: Vain\Core\Config\Context\Factory\Decorator\Assert\ConfigContextFactoryAssertDecorator
    decorates: app.context.factory.config
    public: false
    arguments: ['@app.context.factory.config.assert.inner']
  connection.storage.assert:
    class: Vain\Core\Connection\Storage\Decorator\Assert\ConnectionStorageAssertDecorator
    decorates: connection.storage
    decoration_priority: 900
    arguments: ['@connection.storage.assert.inner', '@config']
  connection.storage.debug:
    class: Vain\Core\Connection\Storage\Decorator\Logger\ConnectionStorageLoggerDecorator
    decorates: connection.storage
    decoration_priority: 1000
    arguments: ['@connection.storage.debug.inner', '@logger.connection']
  event.config.factory.assert:
    class: Vain\Core\Event\Config\Factory\Decorator\Assert\EventConfigFactoryAssertDecorator
    decorates: event.config.factory
    decoration_priority: 1000
    arguments: ['@event.config.factory.assert.inner']
  event.handler.factory.assert:
    class: Vain\Core\Event\Handler\Factory\Decorator\EventHandlerFactoryAssertDecorator
    decorates: event.handler.factory
    decoration_priority: 1000
    arguments: ['@event.handler.factory.assert.inner', '@app.di']
  event.handler.factory.debug:
    class: Vain\Core\Event\Handler\Factory\Decorator\EventHandlerFactoryLoggerDecorator
    decorates: event.handler.factory
    arguments: ['@event.handler.factory.debug.inner', '@logger.event']
  event.dispatcher.debug:
    class: Vain\Core\Event\Dispatcher\Decorator\Logger\EventDispatcherLoggerDecorator
    decorates: event.dispatcher
    decoration_priority: 1000
    arguments: ['@event.dispatcher.debug.inner', '@logger.event']
  http.response.emitter.factory.debug:
    class: Vain\Core\Http\Response\Emitter\Factory\Decorator\EmitterFactoryLoggerDecorator
    decorates: http.response.emitter.factory
    decoration_priority: 1000
    arguments: ['@http.emitter.factory.debug.inner', '@logger.http']
  operation.collection.factory.debug:
    class: Vain\Core\Operation\Collection\Factory\Decorator\Logger\CollectionFactoryLoggerDecorator
    decorates: operation.collection.factory
    decoration_priority: 1000
    arguments: ['@operation.collection.factory.debug.inner', '@logger.operation', '@id.generator.string.random']
  operation.factory.debug:
    class: Vain\Core\Operation\Factory\Decorator\Logger\OperationFactoryLoggerDecorator
    decorates: operation.factory
    decoration_priority: 1000
    arguments: ['@operation.factory.debug.inner', '@logger.operation', '@id.generator.string.random']
  queue.storage.assert:
    class: Vain\Core\Queue\Storage\Decorator\Assert\QueueStorageAssertDecorator
    decorates: queue.storage
    arguments: ['@queue.storage.assert.inner', '@config']
  security.config.factory.assert:
    decorates: security.config.factory
    decoration_priority: 1000
    class: Vain\Core\Security\Config\Factory\Decorator\Assert\SecurityConfigFactoryAssertDecorator
    arguments: ['@security.config.factory.assert.inner']
  security.access.control.ownership.assert:
    decorates: security.access.control.ownership
    decoration_priority: 1000
    class: Vain\Core\Security\Ownership\Decorator\Assert\OwnershipAccessControlAssertDecorator
    arguments: ['@security.access.control.ownership.assert.inner']
  security.access.control.ownership.debug:
    decorates: security.access.control.ownership
    decoration_priority: 100
    class: Vain\Core\Security\Access\Decorator\Logger\AccessControlLoggerDecorator
    arguments: ['@security.access.control.ownership.debug.inner', '@logger.security']
  security.access.control.role.assert:
    decorates: security.access.control.role
    decoration_priority: 1000
    class: Vain\Core\Security\Role\Decorator\Assert\RoleAccessControlAssertDecorator
    arguments: ['@security.access.control.role.assert.inner']
  security.access.control.role.debug:
    decorates: security.access.control.role
    decoration_priority: 100
    class: Vain\Core\Security\Access\Decorator\Logger\AccessControlLoggerDecorator
    arguments: ['@security.access.control.role.debug.inner', '@logger.security']
  security.access.control.voter.assert:
    decorates: security.access.control.voter
    decoration_priority: 1000
    class: Vain\Core\Security\Voter\Decorator\Assert\VoterAccessControlAssertDecorator
    arguments: ['@security.access.control.voter.assert.inner']
  security.access.control.voter.debug:
    decorates: security.access.control.voter
    decoration_priority: 100
    class: Vain\Core\Security\Access\Decorator\Logger\AccessControlLoggerDecorator
    arguments: ['@security.access.control.voter.debug.inner', '@logger.security']